"""
rag/threat_hunting_llm.py — Threat Hunting Automation with LLM v10.0

Uses Claude API for automated threat hunting and incident analysis:
  • Security log analysis via Claude (natural language understanding of events)
  • Threat intelligence correlation (matching logs to known attack patterns)
  • Incident timeline reconstruction (building narrative from fragmented logs)
  • Hypothesis generation (suggesting what attacker might do next)
  • IOC (Indicator of Compromise) extraction from unstructured text
  • Attack phase identification (reconnaissance, exploitation, exfiltration)
  • Remediation recommendations (prioritized by impact and urgency)

Augments automated detection with LLM reasoning for complex investigations.
Reduces analyst cognitive load by synthesizing and contextualizing findings.
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger("shadow.rag.threat_hunting")


class HuntingType(Enum):
    LOG_ANALYSIS = "log_analysis"
    THREAT_CORRELATION = "threat_correlation"
    IOC_EXTRACTION = "ioc_extraction"
    ATTACK_PHASE = "attack_phase_identification"
    HYPOTHESIS = "hypothesis_generation"
    TIMELINE = "timeline_reconstruction"


@dataclass
class LogEntry:
    """Security log entry."""
    timestamp: float
    source: str  # "firewall", "ids", "endpoint", "application"
    event_type: str  # "connection", "exploit", "file_access", etc
    raw_message: str
    structured_data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HuntingResult:
    """Result from LLM-assisted threat hunting."""
    hunt_type: HuntingType
    input_logs: int
    findings: List[str]
    confidence: float
    reasoning: str
    iocs: List[str] = field(default_factory=list)  # Indicators of compromise
    recommendations: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)


@dataclass
class ThreatHypothesis:
    """Hypothesis generated by LLM about ongoing attack."""
    description: str
    likely_attacker_goal: str
    next_likely_actions: List[str]
    confidence: float
    supporting_evidence: List[str]


class LogAnalyzer:
    """
    Analyzes security logs with pattern recognition and LLM reasoning.
    """

    def __init__(self):
        self._logs: List[LogEntry] = []
        self._analysis_results: List[HuntingResult] = []

    def ingest_logs(self, logs: List[LogEntry]) -> None:
        """Ingest security logs for analysis."""
        self._logs.extend(logs)
        logger.info(f"Ingested {len(logs)} logs, total {len(self._logs)} in buffer")

    def identify_suspicious_patterns(self) -> HuntingResult:
        """
        Identify suspicious patterns in logs.
        In production, would call Claude API here.
        """
        if not self._logs:
            return HuntingResult(
                hunt_type=HuntingType.LOG_ANALYSIS,
                input_logs=0,
                findings=[],
                confidence=0.0,
                reasoning="No logs to analyze"
            )

        # Simulate LLM analysis
        findings = []
        iocs = []

        # Group logs by source
        by_source = {}
        for log in self._logs:
            if log.source not in by_source:
                by_source[log.source] = []
            by_source[log.source].append(log)

        # Detect suspicious patterns
        for source, logs_group in by_source.items():
            if len(logs_group) > 100:
                findings.append(f"High volume of events from {source} ({len(logs_group)} events)")

        # Detect potential lateral movement
        unique_sources = set(l.structured_data.get("src_ip", "") for l in self._logs if "src_ip" in l.structured_data)
        unique_targets = set(l.structured_data.get("dst_ip", "") for l in self._logs if "dst_ip" in l.structured_data)
        if len(unique_sources) > 5 and len(unique_targets) > 10:
            findings.append("Potential lateral movement detected (many sources accessing many targets)")
            iocs.extend(list(unique_sources))

        result = HuntingResult(
            hunt_type=HuntingType.LOG_ANALYSIS,
            input_logs=len(self._logs),
            findings=findings,
            confidence=0.75 if findings else 0.3,
            reasoning="Pattern analysis identified unusual activity patterns",
            iocs=iocs
        )
        self._analysis_results.append(result)
        return result

    def extract_iocs(self) -> List[str]:
        """Extract IOCs from logs."""
        iocs = set()

        for log in self._logs:
            # Extract IPs
            if "src_ip" in log.structured_data:
                iocs.add(f"IP:{log.structured_data['src_ip']}")
            if "dst_ip" in log.structured_data:
                iocs.add(f"IP:{log.structured_data['dst_ip']}")

            # Extract domains
            if "domain" in log.structured_data:
                iocs.add(f"DOMAIN:{log.structured_data['domain']}")

            # Extract file hashes
            if "file_hash" in log.structured_data:
                iocs.add(f"HASH:{log.structured_data['file_hash']}")

        return list(iocs)


class AttackPhaseClassifier:
    """
    Classifies logs into attack lifecycle phases.
    """

    def __init__(self):
        self._phase_indicators = {
            "reconnaissance": ["port_scan", "service_enum", "network_discovery"],
            "exploitation": ["exploit_attempt", "shell_execution", "privesc"],
            "lateral_movement": ["credential_dump", "lateral_hop", "pass_the_hash"],
            "persistence": ["scheduled_task", "registry_modification", "rootkit"],
            "exfiltration": ["data_transfer", "bulk_download", "c2_beacon"],
        }

    def classify_logs(self, logs: List[LogEntry]) -> Dict[str, List[LogEntry]]:
        """Classify logs by attack phase."""
        classified = {phase: [] for phase in self._phase_indicators}

        for log in logs:
            for phase, indicators in self._phase_indicators.items():
                if any(ind in log.event_type.lower() for ind in indicators):
                    classified[phase].append(log)
                    break

        return classified

    def identify_phase_sequence(self, logs: List[LogEntry]) -> List[Tuple[str, float]]:
        """
        Identify sequence of attack phases (timeline).
        Returns list of (phase, timestamp)
        """
        classified = self.classify_logs(logs)
        phases_by_time = []

        for phase, phase_logs in classified.items():
            if phase_logs:
                first_time = min(log.timestamp for log in phase_logs)
                phases_by_time.append((phase, first_time))

        phases_by_time.sort(key=lambda x: x[1])
        return phases_by_time


class ThreatHypothesisGenerator:
    """
    Generates hypotheses about ongoing attacks.
    """

    def generate_hypothesis(
        self,
        classified_logs: Dict[str, List[LogEntry]],
        iocs: List[str],
    ) -> ThreatHypothesis:
        """
        Generate threat hypothesis from log patterns.
        In production, would call Claude API for reasoning.
        """
        # Simulate LLM reasoning
        goals = []
        next_actions = []
        confidence = 0.0

        if classified_logs.get("reconnaissance") and classified_logs.get("exploitation"):
            goals.append("Persistent network foothold")
            next_actions.append("Establish C2 communication")
            next_actions.append("Deploy payload to additional systems")
            confidence = 0.85

        if classified_logs.get("lateral_movement"):
            goals.append("Domain dominance")
            next_actions.append("Compromise domain controller")
            next_actions.append("Deploy backd doors on key systems")
            confidence = 0.90

        if classified_logs.get("exfiltration"):
            goals.append("Data theft")
            next_actions.append("Continue exfiltration to avoid detection")
            next_actions.append("Cover tracks and remove evidence")
            confidence = 0.95

        if not goals:
            goals.append("Unknown objective - investigation ongoing")
            next_actions.append("Monitor for additional suspicious activity")
            confidence = 0.4

        supporting_evidence = []
        for phase, logs in classified_logs.items():
            if logs:
                supporting_evidence.append(f"{len(logs)} events in {phase} phase")

        return ThreatHypothesis(
            description=f"Multi-phase attack detected with {len([p for p in classified_logs.values() if p])} active phases",
            likely_attacker_goal=" OR ".join(goals),
            next_likely_actions=next_actions,
            confidence=confidence,
            supporting_evidence=supporting_evidence
        )


class ThreatHuntingLLM:
    """
    Main threat hunting engine using LLM-assisted analysis.
    """

    def __init__(self):
        self._log_analyzer = LogAnalyzer()
        self._phase_classifier = AttackPhaseClassifier()
        self._hypothesis_generator = ThreatHypothesisGenerator()
        self._active_investigations: Dict[str, HuntingResult] = {}
        self._hypotheses: List[ThreatHypothesis] = []
        self._stats = {
            "logs_analyzed": 0,
            "hunts_performed": 0,
            "hypotheses_generated": 0,
            "iocs_extracted": 0,
        }

    def analyze_incident(
        self,
        logs: List[LogEntry],
        investigation_id: str
    ) -> Dict[str, Any]:
        """
        Perform comprehensive analysis of incident.
        """
        logger.info(f"Starting analysis of incident {investigation_id} with {len(logs)} logs")

        self._log_analyzer.ingest_logs(logs)
        self._stats["logs_analyzed"] += len(logs)
        self._stats["hunts_performed"] += 1

        # Pattern analysis
        pattern_result = self._log_analyzer.identify_suspicious_patterns()

        # IOC extraction
        iocs = self._log_analyzer.extract_iocs()
        self._stats["iocs_extracted"] += len(iocs)

        # Attack phase classification
        classified = self._phase_classifier.classify_logs(logs)
        phase_sequence = self._phase_classifier.identify_phase_sequence(logs)

        # Hypothesis generation
        hypothesis = self._hypothesis_generator.generate_hypothesis(classified, iocs)
        self._hypotheses.append(hypothesis)
        self._stats["hypotheses_generated"] += 1

        # Build recommendations
        recommendations = []
        if hypothesis.confidence > 0.8:
            recommendations.append("IMMEDIATE: Isolate affected systems from network")
            recommendations.append("Capture memory dumps from all compromised hosts")
            recommendations.append("Preserve disk images for forensics")

        result = HuntingResult(
            hunt_type=HuntingType.LOG_ANALYSIS,
            input_logs=len(logs),
            findings=pattern_result.findings,
            confidence=hypothesis.confidence,
            reasoning=f"Attack lifecycle: {' -> '.join(p[0] for p in phase_sequence)}",
            iocs=iocs,
            recommendations=recommendations
        )

        self._active_investigations[investigation_id] = result
        logger.info(f"Analysis complete for {investigation_id}: {hypothesis.confidence:.1%} confidence")

        return {
            "investigation_id": investigation_id,
            "pattern_analysis": pattern_result,
            "attack_phases": [(p[0], p[1]) for p in phase_sequence],
            "hypothesis": {
                "description": hypothesis.description,
                "goal": hypothesis.likely_attacker_goal,
                "next_actions": hypothesis.next_likely_actions,
                "confidence": hypothesis.confidence,
            },
            "iocs": iocs,
            "recommendations": recommendations,
        }

    @property
    def stats(self) -> Dict[str, Any]:
        return dict(self._stats)

    @property
    def active_cases(self) -> List[str]:
        return list(self._active_investigations.keys())


_hunting_engine: Optional[ThreatHuntingLLM] = None


def get_threat_hunting_engine() -> ThreatHuntingLLM:
    global _hunting_engine
    if _hunting_engine is None:
        _hunting_engine = ThreatHuntingLLM()
    return _hunting_engine


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    engine = get_threat_hunting_engine()

    # Simulate incident logs
    logs = [
        LogEntry(
            timestamp=time.time() - 3600,
            source="ids",
            event_type="port_scan",
            raw_message="Port scan detected",
            structured_data={"src_ip": "192.0.2.10", "ports": "1-65535"}
        ),
        LogEntry(
            timestamp=time.time() - 3000,
            source="ids",
            event_type="exploit_attempt",
            raw_message="Exploit attempt detected",
            structured_data={"src_ip": "192.0.2.10", "target": "192.168.1.100"}
        ),
        LogEntry(
            timestamp=time.time() - 1800,
            source="endpoint",
            event_type="privesc",
            raw_message="Privilege escalation detected",
            structured_data={"host": "192.168.1.100", "method": "kernel_exploit"}
        ),
        LogEntry(
            timestamp=time.time() - 900,
            source="firewall",
            event_type="data_transfer",
            raw_message="Large data transfer",
            structured_data={"src_ip": "192.168.1.100", "dst_ip": "1.2.3.4", "bytes": 5000000}
        ),
    ]

    result = engine.analyze_incident(logs, "INC-2024-001")

    print(f"\n=== Incident Analysis Results ===")
    print(f"Hypothesis Confidence: {result['hypothesis']['confidence']:.1%}")
    print(f"Attacker Goal: {result['hypothesis']['goal']}")
    print(f"Next Likely Actions: {result['hypothesis']['next_actions']}")
    print(f"\nIOCs Identified: {len(result['iocs'])}")
    print(f"Recommendations: {len(result['recommendations'])}")
    for rec in result['recommendations']:
        print(f"  - {rec}")

    print(f"\nStats: {engine.stats}")
    print("Threat Hunting LLM OK")
